# Generated by Django 4.2.21 on 2025-06-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(choices=[('USA', 'America'), ('SWZ', 'Switzerland'), ('AZB', 'Azerbaijan'), ('OHO', 'Ohio')], max_length=10),
        ),
    ]
